multible models


In [0]:
import numpy
import torch
import torchvision
import torchvision.datasets as datasets
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF




mnist_trainset = datasets.MNIST(root='./data', train=True, download=True, transform=torchvision.transforms.ToTensor())
mnist_testset =datasets.MNIST(root='./data', train=False, download=True, transform=torchvision.transforms.ToTensor())

mnist_testset=mnist_testset

print(mnist_trainset.data.shape)
print(mnist_trainset.data[0:2000].view(-1,28*28).shape)
kernel = 1.0 * RBF(28*28)



gpc = GaussianProcessClassifier(kernel=kernel,n_restarts_optimizer=0,random_state=None,multi_class="one_vs_rest",max_iter_predict=100,n_jobs=1)
param=gpc.get_params()
print(param)
gpc=gpc.fit(mnist_trainset.data[0:1000].view(-1,28*28), mnist_trainset.targets[0:1000])
from numpy import load
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.decomposition import FastICA, PCA
from sklearn.metrics import classification_report

data_ad = load('/data/fmri/cv/hippocampus/hipp_ad.npz')
lst_ad=data_ad['masked_voxels']
data_con = load('/data/fmri/cv/hippocampus/hipp_con.npz')
import numpy as np
lst_con=data_con['masked_voxels']
print(np.shape(lst_ad))
print(np.shape(lst_con))
lst=np.hstack((lst_ad,lst_con)).T
print(np.shape(lst))
labels_ad=np.ones((np.shape(lst_ad)[1],1))
labels_con=np.zeros((np.shape(lst_con)[1],1))
print(np.shape(labels_ad))
print(np.shape(labels_con))
labels=np.vstack((labels_ad,labels_con))
print(np.shape(labels))
data_train, data_test, labels_train, labels_test = train_test_split(lst, labels, test_size=0.20, random_state=42)


kernel = 1.0 * RBF(214)
'''
S=data_train
T=data_test
S /= S.std(axis=0)
T /= T.std(axis=0)
ica = FastICA(n_components=14)
S_ = ica.fit_transform(S)
T_=ica.fit_transform(T)
'''
gpc = GaussianProcessClassifier(kernel=kernel,n_restarts_optimizer=5,random_state=None,multi_class="one_vs_rest",max_iter_predict=100,n_jobs=-1)
gpc=gpc.fit(data_train, labels_train)
print('')
print('accuracy on trainingset:',gpc.score(data_train,labels_train))
print('accuracy on testset:',gpc.score(data_test, labels_test))
print("confusion matrix for the training")
cm_train = confusion_matrix(labels_train, gpc.predict(data_train))
print(cm_train)
print(classification_report(labels_train, gpc.predict(data_train), labels=[0, 1]))
print("confusion matrix for the testing")
cm_test = confusion_matrix(labels_test, gpc.predict(data_test))
print(cm_test)
print('')
print(classification_report(labels_test, gpc.predict(data_test), labels=[0, 1]))


print(gpc.score(mnist_trainset.data[0:1000].view(-1,28*28), mnist_trainset.targets[0:1000]))
print(gpc.score(mnist_testset.data[0:600].view(-1,28*28), mnist_testset.targets[0:600]))
print(gpc.predict(mnist_trainset.data[0:20].view(-1,28*28)))
print(gpc.predict_proba(mnist_trainset.data[0:20].view(-1,28*28)))
print(mnist_trainset.targets[0:20])
print(gpc.predict(mnist_testset.data[0:20].view(-1,28*28)))
print(gpc.predict_proba(mnist_testset.data[0:20].view(-1,28*28)))
print(mnist_testset.targets[0:20])

torch.Size([60000, 28, 28])
torch.Size([2000, 784])
{'copy_X_train': True, 'kernel__k1': 1**2, 'kernel__k2': RBF(length_scale=784), 'kernel__k1__constant_value': 1.0, 'kernel__k1__constant_value_bounds': (1e-05, 100000.0), 'kernel__k2__length_scale': 784, 'kernel__k2__length_scale_bounds': (1e-05, 100000.0), 'kernel': 1**2 * RBF(length_scale=784), 'max_iter_predict': 100, 'multi_class': 'one_vs_rest', 'n_jobs': 1, 'n_restarts_optimizer': 0, 'optimizer': 'fmin_l_bfgs_b', 'random_state': None, 'warm_start': False}
1.0
0.88
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
[[0.03705204 0.09328758 0.0574662  0.13476006 0.00519546 0.46731385
  0.02476367 0.08315068 0.04870697 0.04830349]
 [0.57957451 0.0989707  0.04426856 0.0229423  0.00930207 0.05342875
  0.01551473 0.05002403 0.04211807 0.08385628]
 [0.04656588 0.08721258 0.08870846 0.099764   0.36328922 0.08851655
  0.07070356 0.05555895 0.04323299 0.05644781]
 [0.02633139 0.69889219 0.05706056 0.02768617 0.02629755 0.03375195
  0.02782101 0.040

In [0]:
from sklearn import svm
clf = svm.SVC(gamma='scale', decision_function_shape='ovo',probability=True)
clf.fit(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000]) 
print(clf.score(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000]))
print(clf.score(mnist_testset.data[0:600].view(-1,28*28), mnist_testset.targets[0:600]))
print(clf.predict(mnist_trainset.data[0:20].view(-1,28*28)))
print(clf.predict_proba(mnist_trainset.data[0:20].view(-1,28*28)))
print(mnist_trainset.targets[0:20])
print(clf.predict(mnist_testset.data[0:20].view(-1,28*28)))
print(clf.predict_proba(mnist_testset.data[0:20].view(-1,28*28)))
print(mnist_testset.targets[0:20])

0.9815
0.91
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
[[2.73368223e-03 2.51455464e-03 2.61412794e-03 3.38289661e-02
  1.77969306e-04 9.47924570e-01 8.68761619e-04 1.83359265e-03
  3.62160176e-03 3.88217398e-03]
 [9.92072862e-01 5.85776504e-04 1.02506526e-03 1.65999791e-03
  5.90936971e-05 8.93924206e-04 5.25207549e-04 3.62425405e-04
  3.97098479e-04 2.41854879e-03]
 [1.40933249e-03 1.42285956e-03 6.71249872e-03 3.90632748e-03
  9.70456241e-01 2.20051709e-03 1.76506694e-03 5.51714576e-03
  2.02347283e-03 4.58653763e-03]
 [5.98719774e-04 9.77583648e-01 5.95221337e-03 1.29620444e-03
  1.23260535e-03 6.97766303e-04 4.25300130e-04 4.79033216e-03
  6.92695050e-03 4.96259678e-04]
 [3.41478397e-04 2.47989954e-03 5.36572403e-04 8.27309051e-04
  7.30577072e-03 6.91844111e-04 1.61687682e-04 8.37067925e-03
  1.66535417e-03 9.77619405e-01]
 [3.51860577e-03 6.89826018e-04 9.68004261e-01 6.16443046e-03
  1.08541201e-03 3.57293366e-03 5.14876229e-04 1.52005613e-03
  6.59159568e-03 8.33800354e-03]
 [3.

In [0]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=100)
clf.fit(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000])   
print(clf.score(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000]))
print(clf.score(mnist_testset.data[0:600].view(-1,28*28), mnist_testset.targets[0:600]))
print(clf.predict(mnist_trainset.data[0:20].view(-1,28*28)))
print(mnist_trainset.targets[0:20])
print(clf.predict(mnist_testset.data[0:20].view(-1,28*28)))
print(mnist_testset.targets[0:20])

0.9915
0.8116666666666666
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
tensor([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9])
[7 2 1 0 4 1 4 9 4 9 0 6 9 0 1 5 9 7 3 4]
tensor([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4])


In [0]:
from sklearn.neighbors.nearest_centroid import NearestCentroid
clf = NearestCentroid(metric='euclidean')
clf.fit(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000])
print(clf.score(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000]))
print(clf.score(mnist_testset.data[0:600].view(-1,28*28), mnist_testset.targets[0:600]))
print(clf.predict(mnist_trainset.data[0:20].view(-1,28*28)))
print(mnist_trainset.targets[0:20])
print(clf.predict(mnist_testset.data[0:20].view(-1,28*28)))
print(mnist_testset.targets[0:20])

0.8105
0.7333333333333333
[3 0 4 1 9 2 1 3 1 4 3 1 3 6 1 7 2 8 6 9]
tensor([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9])
[7 2 1 0 4 1 4 9 2 9 0 2 9 0 1 5 4 7 5 4]
tensor([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4])


In [0]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000])
print(clf.score(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000]))
print(clf.score(mnist_testset.data[0:600].view(-1,28*28), mnist_testset.targets[0:600]))
print(clf.predict(mnist_trainset.data[0:20].view(-1,28*28)))
print(clf.predict_proba(mnist_trainset.data[0:20].view(-1,28*28)))
print(mnist_trainset.targets[0:20])
print(clf.predict(mnist_testset.data[0:20].view(-1,28*28)))
print(clf.predict_proba(mnist_testset.data[0:20].view(-1,28*28)))
print(mnist_testset.targets[0:20])

1.0
0.6766666666666666
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
tensor([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9])
[7 0 1 0 9 1 4 9 9 9 0 6 9 0 1 5 9 7 6 4]
tensor([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4])


In [0]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(1000,500,50))
clf = clf.fit(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000])
print(clf.score(mnist_trainset.data[0:2000].view(-1,28*28), mnist_trainset.targets[0:2000]))
print(clf.score(mnist_testset.data[0:600].view(-1,28*28), mnist_testset.targets[0:600]))
print(clf.predict(mnist_trainset.data[0:20].view(-1,28*28)))
print(clf.predict_proba(mnist_trainset.data[0:20].view(-1,28*28)))
print(mnist_trainset.targets[0:20])
print(clf.predict(mnist_testset.data[0:20].view(-1,28*28)))
print(clf.predict_proba(mnist_testset.data[0:20].view(-1,28*28)))
print(mnist_testset.targets[0:20])

0.995
0.8233333333333334
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
[[4.77020477e-11 4.08234027e-19 7.66758892e-11 2.87143101e-07
  2.13925829e-05 9.99978309e-01 2.71418290e-14 2.13252584e-09
  9.40135206e-09 3.68229144e-14]
 [1.00000000e+00 1.40758362e-34 7.13667171e-24 2.02847790e-54
  6.96163067e-55 2.11493393e-45 3.11263126e-26 3.71898964e-33
  6.24808927e-61 9.59301997e-27]
 [2.19317546e-24 5.27109620e-45 5.13719421e-12 3.43800116e-41
  1.00000000e+00 2.64894668e-22 4.90931233e-37 3.71124755e-31
  3.00065520e-36 5.88677481e-29]
 [1.33725405e-25 9.99998754e-01 2.25620116e-21 1.01527303e-23
  3.06762262e-17 6.29122376e-22 2.49788435e-26 1.24602998e-06
  5.36574297e-27 4.91462406e-15]
 [3.47810708e-17 2.55524548e-15 6.57954008e-17 6.40179844e-33
  1.56302739e-15 1.61786452e-31 3.79631105e-36 1.17602448e-18
  1.87029814e-22 1.00000000e+00]
 [5.83260692e-05 9.50224430e-17 9.99922925e-01 4.96476530e-13
  1.73088836e-05 1.44018693e-06 1.55130737e-14 5.05001325e-11
  4.03938287e-14 9.19367